apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-helm
  labels:
    app: nginx
    demo: helm
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      demo: helm
  template: # pod defination
    metadata:
      labels:
        app: nginx
        demo: helm
    spec:
      containers:
      - name: nginx
        image: nginx
